# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.11.4

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - git config user.name "calvin"
  - git config user.email "calvin_cheung@outlook.com"

# Start: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo g

# 设置git提交名，邮箱
after_script:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://${GH_TOKEN}@github.com/calvingit/calvingit.github.io.git master

# End: Build LifeCycle
notifications:
  email:
    - calvin_cheung@outlook.com
  on_success: change
  on_failure: always